name: super_enum
description: Create super-powered enums similar to sealed classes in Kotlin.
version: 0.6.0
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  meta: ^1.2.3
  equatable: ^2.0.0

# Adding dev dependencies
# just for showcasing an example
dev_dependencies:
  http: ^0.13.0
  build_runner: ^2.0.0
  super_enum_generator:
    path: ../super_enum_generator
