name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 0.6.0
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  # Specify a specific version or a version constraint
  # for "super_enum" before publishing the package.
  super_enum: ^0.5.0
  source_gen: ^0.9.7+1
  analyzer: '>=0.40.0 <2.0.0'
  build: '>=0.12.6 <2.0.0'
  code_builder: ^3.5.0
  dart_style: ^1.3.7

dev_dependencies:
  test: ^1.15.4
  build_runner: ^1.10.3
  source_gen_test: ^0.1.1+1