name: super_enum_generator
description: Dev-dependency to generate sealed classes and when statements together with the super_enum.dart package.
version: 0.6.1
homepage: https://github.com/xsahil03x/super_enum

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

  # Specify a specific version or a version constraint
  # for "super_enum" before publishing the package.
  super_enum: ^0.5.0
  source_gen: ^1.2.6
  analyzer: '^5.2.0'
  build: ^2.3.1
  code_builder: ^4.4.0
  dart_style: ^2.2.4

dev_dependencies:
  test: ^1.22.1
  build_runner: ^2.3.3
  source_gen_test: ^1.0.4
