name: Dart CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: google/dart:latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: cd super_enum_generator && pub get
      - name: format
        run: dartfmt -n --set-exit-if-changed .
      - name: Run tests
        run: cd super_enum_generator && pub run test
      - name: Collect coverage
        run: cd super_enum_generator && ./tool/run_coverage.sh
      - name: Report CodeCov
        uses: codecov/codecov-action@v1.0.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: super_enum_generator/coverage/lcov.info